# Forefront Engine Configuration
# 
# This file is auto-generated by Forefront. Uncomment and modify as needed.

Forefront.setup do |config|
  # ===== DEFAULT CONFIGURATION (Forefront::Admin with Devise) =====
  # Uncomment the lines below if you want to use Forefront's built-in Admin model.
  # This is the default and requires no changes.
  
  # config.admin_class = "Forefront::Admin"
  # config.authenticate_with = :authenticate_admin!
  # config.current_admin_method = :current_admin


  # ===== CUSTOM HOST APP AUTHENTICATION =====
  # Uncomment and modify the lines below to use your own user model for authentication.
  # This allows Forefront to use your existing authentication system.
  
  # config.admin_class = "User"                    # Your user model class name
  # config.authenticate_with = :authenticate_user! # Your auth method (Devise, custom, etc.)
  # config.current_admin_method = :current_user   # Your current user method
  
  # IMPORTANT: Your user model must implement a super_admin? method:
  #   def super_admin?
  #     role == 'admin' || is_admin == true  # adjust to your logic
  #   end
end
